In [1]:
#Importing all the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as pt


In [2]:
np.set_printoptions(suppress = True)

In [3]:
data_set = pd.read_csv("E:\Python All in One\DATA_SETS\Machine Learning A-Z Template Folder\Part 2 - Regression\Section 5 - Multiple Linear Regression\Multiple_Linear_Regression\Startups.csv")

In [4]:
#Importing the data_sets
data_set.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [5]:
#Selecting the Dependent and Independent variables

x = data_set.iloc[:, :-1].values
y = data_set.iloc[:,-1].values

print(x)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [6]:
#Since we can see that the x variable has some ctegorical data so we need to handle it.

#Handling the categorical variable using Scikit-Learn

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
x[:,3] = labelencoder.fit_transform(x[:, 3])

onehotencoder = OneHotEncoder(categorical_features=[3])
x = onehotencoder.fit_transform(x).toarray()


C:\Users\Gaurav SINGH\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Gaurav SINGH\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [7]:
#Avoiding Dummy Varible Trap

z = x[:,1:]
print(z)

[[     0.        1.   165349.2  136897.8  471784.1 ]
 [     0.        0.   162597.7  151377.59 443898.53]
 [     1.        0.   153441.51 101145.55 407934.54]
 [     0.        1.   144372.41 118671.85 383199.62]
 [     1.        0.   142107.34  91391.77 366168.42]
 [     0.        1.   131876.9   99814.71 362861.36]
 [     0.        0.   134615.46 147198.87 127716.82]
 [     1.        0.   130298.13 145530.06 323876.68]
 [     0.        1.   120542.52 148718.95 311613.29]
 [     0.        0.   123334.88 108679.17 304981.62]
 [     1.        0.   101913.08 110594.11 229160.95]
 [     0.        0.   100671.96  91790.61 249744.55]
 [     1.        0.    93863.75 127320.38 249839.44]
 [     0.        0.    91992.39 135495.07 252664.93]
 [     1.        0.   119943.24 156547.42 256512.92]
 [     0.        1.   114523.61 122616.84 261776.23]
 [     0.        0.    78013.11 121597.55 264346.06]
 [     0.        1.    94657.16 145077.58 282574.31]
 [     1.        0.    91749.16 114175.79 2949

In [8]:
len(x)

50

In [9]:
#Split the DataSet into Training Set and Test Set
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(z, y, test_size=.2, random_state = 0)


In [10]:
len(x_train)

40

In [11]:
#Fitting the model to our training dataset
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
#Predicting the values using our Test DataSet

#organising whole dataset
y_pred = regressor.predict(x_test)
s1 = pd.DataFrame(x_test, columns = ['DUMMY1','DUMMY2','R&D', 'MARKETING', 'ADMIN']).reset_index()
dfx = pd.Series(y_test, name="Y_test")
s1.drop('index', axis=1)
s1 = s1.join(dfx)

dfx2 = pd.Series(y_pred, name='Y_pred')
s1 = s1.join(dfx2)

s1 = s1.drop('index', axis=1)

s1['SSE'] = s1["Y_test"]-s1["Y_pred"]

s1


DUMMY1  DUMMY2        R&D  MARKETING      ADMIN     Y_test         Y_pred  \
0     1.0     0.0   66051.52  182645.56  118148.20  103282.38  103015.201598   
1     0.0     0.0  100671.96   91790.61  249744.55  144259.40  132582.277608   
2     1.0     0.0  101913.08  110594.11  229160.95  146121.95  132447.738452   
3     1.0     0.0   27892.92   84710.77  164470.71   77798.83   71976.098513   
4     1.0     0.0  153441.51  101145.55  407934.54  191050.39  178537.482211   
5     0.0     1.0   72107.60  127864.55  353183.81  105008.31  116161.242302   
6     0.0     1.0   20229.59   65947.93  185265.10   81229.06   67851.692097   
7     0.0     1.0   61136.38  152701.92   88218.23   97483.56   98791.733747   
8     1.0     0.0   73994.56  122782.75  303319.26  110352.25  113969.435330   
9     1.0     0.0  142107.34   91391.77  366168.42  166187.94  167921.065695   

            SSE  
0    267.178402  
1  11677.122392  
2  13674.211548  
3   5822.731487  
4  12512.907789  
5 -11152.932302  
6  13377.367903  
7  -1308.173747  
8  -3617.185330  
9  -1733.125695

In [13]:
s1['SSE'].max()

13674.211548252468

In [14]:
regressor.score(x_test,y_test)*100

93.47068473282803

As we saw that the Multiple Linear Regression can be easily done with normal Scikit-Learn Library, but this is not the optimal model, so we need to construct an optimal model with the help of Model Constructions methods.

We will use " BACKWARD ELIMINATION METHOD "

In [15]:
#Preparing the dataset for the optimal backward elmination method
import statsmodels.api as sm

z = np.append(arr = np.ones((50,1)), values = z, axis=1)

z
# #Now applying statsmodel.api for the model optimizaion
# x_opt = z[:,[0,1,2,3,4,5]]
# regressor = sm.OLS(endog = y, exdog = x_opt).fit()

array([[     1.  ,      0.  ,      1.  , 165349.2 , 136897.8 , 471784.1 ],
       [     1.  ,      0.  ,      0.  , 162597.7 , 151377.59, 443898.53],
       [     1.  ,      1.  ,      0.  , 153441.51, 101145.55, 407934.54],
       [     1.  ,      0.  ,      1.  , 144372.41, 118671.85, 383199.62],
       [     1.  ,      1.  ,      0.  , 142107.34,  91391.77, 366168.42],
       [     1.  ,      0.  ,      1.  , 131876.9 ,  99814.71, 362861.36],
       [     1.  ,      0.  ,      0.  , 134615.46, 147198.87, 127716.82],
       [     1.  ,      1.  ,      0.  , 130298.13, 145530.06, 323876.68],
       [     1.  ,      0.  ,      1.  , 120542.52, 148718.95, 311613.29],
       [     1.  ,      0.  ,      0.  , 123334.88, 108679.17, 304981.62],
       [     1.  ,      1.  ,      0.  , 101913.08, 110594.11, 229160.95],
       [     1.  ,      0.  ,      0.  , 100671.96,  91790.61, 249744.55],
       [     1.  ,      1.  ,      0.  ,  93863.75, 127320.38, 249839.44],
       [     1.  ,      0

numpy.ndarray

In [16]:
x_opt = z[:,[0,1,2,3,4,5]]
regressor_ols = sm.OLS(y,x_opt).fit()
regressor_ols.summary()



<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Fri, 27 Dec 2019   Prob (F-statistic):           1.34e-27
Time:                        18:17:57   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.013e+04   6884.820      7.281      0.000    3.62e+04     6.4e+04
x1           198.7888   3371.007      0.059      0.953   -6595.030    6992.607
x2           -41.8870   3256.039     -0.013      0.990   -6604.003    6520.229
x3             0.8060      0.046     17.369      0.000       0.712       0.900
x4            -0.0270      0.052     -0.517      0.608      -0.132       0.078
x5             0.0270      0.017      1.574      0.123      -0.008       0.062
==============================================================================
Omnibus:                       14.782   Durbin-Watson:                   1.283
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.266
Skew:                          -0.948   Prob(JB):                     2.41e-05
Kurtosis:                       5.572   Cond. No.                     1.45e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [25]:
x_opt

array([[     1.  , 165349.2 ],
       [     1.  , 162597.7 ],
       [     1.  , 153441.51],
       [     1.  , 144372.41],
       [     1.  , 142107.34],
       [     1.  , 131876.9 ],
       [     1.  , 134615.46],
       [     1.  , 130298.13],
       [     1.  , 120542.52],
       [     1.  , 123334.88],
       [     1.  , 101913.08],
       [     1.  , 100671.96],
       [     1.  ,  93863.75],
       [     1.  ,  91992.39],
       [     1.  , 119943.24],
       [     1.  , 114523.61],
       [     1.  ,  78013.11],
       [     1.  ,  94657.16],
       [     1.  ,  91749.16],
       [     1.  ,  86419.7 ],
       [     1.  ,  76253.86],
       [     1.  ,  78389.47],
       [     1.  ,  73994.56],
       [     1.  ,  67532.53],
       [     1.  ,  77044.01],
       [     1.  ,  64664.71],
       [     1.  ,  75328.87],
       [     1.  ,  72107.6 ],
       [     1.  ,  66051.52],
       [     1.  ,  65605.48],
       [     1.  ,  61994.48],
       [     1.  ,  61136.38],
       [

Now we can clearly see that the P-value of x2 column is highest among all so we will remove it and again fit the model.

In [17]:
x_opt = z[:,[0,1,3,4,5]]
regressor_ols = sm.OLS(y,x_opt).fit()
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Fri, 27 Dec 2019   Prob (F-statistic):           8.49e-29
Time:                        18:17:58   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.011e+04   6647.870      7.537      0.000    3.67e+04    6.35e+04
x1           220.1585   2900.536      0.076      0.940   -5621.821    6062.138
x2             0.8060      0.046     17.606      0.000       0.714       0.898
x3            -0.0270      0.052     -0.523      0.604      -0.131       0.077
x4             0.0270      0.017      1.592      0.118      -0.007       0.061
==============================================================================
Omnibus:                       14.758   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.172
Skew:                          -0.948   Prob(JB):                     2.53e-05
Kurtosis:                       5.563   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

Now again the P-value of x1 is much higher so again we will remove the x1 column and fit the model

In [18]:
x_opt = z[:,[0,3,4,5]]
regressor_ols = sm.OLS(y,x_opt).fit()
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Fri, 27 Dec 2019   Prob (F-statistic):           4.53e-30
Time:                        18:17:58   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626      0.000    3.69e+04    6.34e+04
x1             0.8057      0.045     17.846      0.000       0.715       0.897
x2            -0.0268      0.051     -0.526      0.602      -0.130       0.076
x3             0.0272      0.016      1.655      0.105      -0.006       0.060
==============================================================================
Omnibus:                       14.838   Durbin-Watson:                   1.282
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.442
Skew:                          -0.949   Prob(JB):                     2.21e-05
Kurtosis:                       5.586   Cond. No.                     1.40e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.4e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [19]:
#removing the column x2

x_opt = z[:,[0,3,5]]
regressor_ols = sm.OLS(y,x_opt).fit()
regressor_ols.summary()



<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Fri, 27 Dec 2019   Prob (F-statistic):           2.16e-31
Time:                        18:17:58   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.000    4.16e+04    5.24e+04
x1             0.7966      0.041     19.266      0.000       0.713       0.880
x2             0.0299      0.016      1.927      0.060      -0.001       0.061
==============================================================================
Omnibus:                       14.677   Durbin-Watson:                   1.257
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               21.161
Skew:                          -0.939   Prob(JB):                     2.54e-05
Kurtosis:                       5.575   Cond. No.                     5.32e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.32e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [20]:

x_opt = z[:,[0,3]]
regressor_ols = sm.OLS(y,x_opt).fit()
regressor_ols.summary()


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Fri, 27 Dec 2019   Prob (F-statistic):           3.50e-32
Time:                        18:17:58   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.000    4.39e+04    5.41e+04
x1             0.8543      0.029     29.151      0.000       0.795       0.913
==============================================================================
Omnibus:                       13.727   Durbin-Watson:                   1.116
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               18.536
Skew:                          -0.911   Prob(JB):                     9.44e-05
Kurtosis:                       5.361   Cond. No.                     1.65e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.65e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""